/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package patientdashboard;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import util.DatabaseConnection;

/**
 *
 * @author tshiy
 */
public class DoctorMedicalPatientHistory extends javax.swing.JFrame {

    private int doctorId;
    /**
     * Creates new form DoctorMedicalPatientHistory
     */
    public DoctorMedicalPatientHistory(int doctorId) {
        initComponents();
        this.doctorId = doctorId;
        loadMedicalHistory();
    }
    
    // Load medical history records from the database
    private void loadMedicalHistory() {
        DefaultTableModel model = (DefaultTableModel) medicalHistoryTable.getModel();
        model.setRowCount(0);  // Clear existing rows

        String query = "SELECT * FROM medical_history WHERE doctorId = ?";
        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pst = conn.prepareStatement(query)) {

            pst.setInt(1, doctorId);  // Set the doctorId for filtering
            ResultSet rs = pst.executeQuery();

            // Loop through the results and add them to the table
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("recordId"),
                    rs.getString("doctorFirstName"),
                    rs.getString("doctorLastName"),
                    rs.getString("diagnosis"),
                    rs.getString("treatment"),
                    rs.getString("prescriptions"),
                    rs.getDate("appointmentDate")
                });
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading medical history.");
        }
    }

    // Search functionality for filtering the records in the table
    private void btnSearchActionPerformed(ActionEvent evt) {
        String searchText = txtSearch.getText().trim();

        if (searchText.isEmpty()) {
            loadMedicalHistory();  // Reload all records if search text is empty
        } else {
            DefaultTableModel model = (DefaultTableModel) medicalHistoryTable.getModel();
            model.setRowCount(0);  // Clear existing rows

            String query = "SELECT * FROM medical_history WHERE doctorId = ? AND (diagnosis LIKE ? OR prescriptions LIKE ? OR appointmentDate LIKE ?)";
            try (Connection conn = DatabaseConnection.getConnection();
                 PreparedStatement pst = conn.prepareStatement(query)) {

                pst.setInt(1, doctorId);
                pst.setString(2, "%" + searchText + "%");
                pst.setString(3, "%" + searchText + "%");
                pst.setString(4, "%" + searchText + "%");
                ResultSet rs = pst.executeQuery();

                // Add filtered records to the table
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("recordId"),
                        rs.getString("doctorFirstName"),
                        rs.getString("doctorLastName"),
                        rs.getString("diagnosis"),
                        rs.getString("treatment"),
                        rs.getString("prescriptions"),
                        rs.getDate("appointmentDate")
                    });
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error performing search.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NavBtnBack2Dash = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        NavBtnviewAppointment = new javax.swing.JButton();
        NavBtnConsulatation = new javax.swing.JButton();
        NavBtnEditProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicalHistoryTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnViewDetails = new javax.swing.JButton();
        btnAddRecord = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 121, 151));

        NavBtnBack2Dash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NavBtnBack2Dash.setForeground(new java.awt.Color(255, 255, 255));
        NavBtnBack2Dash.setText("Dashboard");
        NavBtnBack2Dash.setBorder(null);
        NavBtnBack2Dash.setBorderPainted(false);
        NavBtnBack2Dash.setContentAreaFilled(false);
        NavBtnBack2Dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtnBack2DashActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jLabel8.setText("Redstone Health Center");

        NavBtnviewAppointment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NavBtnviewAppointment.setForeground(new java.awt.Color(255, 255, 255));
        NavBtnviewAppointment.setText("View Appointments");
        NavBtnviewAppointment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NavBtnviewAppointment.setBorderPainted(false);
        NavBtnviewAppointment.setContentAreaFilled(false);
        NavBtnviewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtnviewAppointmentActionPerformed(evt);
            }
        });

        NavBtnConsulatation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NavBtnConsulatation.setForeground(new java.awt.Color(255, 255, 255));
        NavBtnConsulatation.setText("Consulatation");
        NavBtnConsulatation.setBorder(null);
        NavBtnConsulatation.setBorderPainted(false);
        NavBtnConsulatation.setContentAreaFilled(false);
        NavBtnConsulatation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtnConsulatationActionPerformed(evt);
            }
        });

        NavBtnEditProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NavBtnEditProfile.setForeground(new java.awt.Color(255, 255, 255));
        NavBtnEditProfile.setText("Edit Profile");
        NavBtnEditProfile.setBorder(null);
        NavBtnEditProfile.setBorderPainted(false);
        NavBtnEditProfile.setContentAreaFilled(false);
        NavBtnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NavBtnEditProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NavBtnEditProfile)
                    .addComponent(NavBtnviewAppointment)
                    .addComponent(NavBtnBack2Dash)
                    .addComponent(NavBtnConsulatation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addComponent(NavBtnBack2Dash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NavBtnviewAppointment)
                .addGap(18, 18, 18)
                .addComponent(NavBtnConsulatation)
                .addGap(18, 18, 18)
                .addComponent(NavBtnEditProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Medical History");

        medicalHistoryTable.setBackground(new java.awt.Color(0, 153, 153));
        medicalHistoryTable.setForeground(new java.awt.Color(255, 255, 255));
        medicalHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Doctor First Name", "Doctor Last Name", "Diagnosis", "Treatment", "Prescriptions", "Appointment Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicalHistoryTable);

        txtSearch.setText("Search (date/doctor/prescription)");

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnAddRecord.setText("Add Records");
        btnAddRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecordActionPerformed(evt);
            }
        });

        btnExportPDF.setText("Export to PDF");
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnViewDetails)
                        .addGap(136, 136, 136)
                        .addComponent(btnAddRecord)
                        .addGap(110, 110, 110)
                        .addComponent(btnExportPDF)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails)
                    .addComponent(btnAddRecord)
                    .addComponent(btnExportPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavBtnBack2DashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtnBack2DashActionPerformed
        // TODO add your handling code here:
        new DoctorDash(doctorId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NavBtnBack2DashActionPerformed

    private void NavBtnviewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtnviewAppointmentActionPerformed
        // TODO add your handling code here:
        new viewAppDoctor(doctorId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NavBtnviewAppointmentActionPerformed

    private void NavBtnConsulatationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtnConsulatationActionPerformed
        // TODO add your handling code here:
        new Consultaion(doctorId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NavBtnConsulatationActionPerformed

    private void NavBtnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavBtnEditProfileActionPerformed
        // TODO add your handling code here:
        new EditDoctor(doctorId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NavBtnEditProfileActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = medicalHistoryTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a record to view details.");
            return;
        }

        int recordId = (int) medicalHistoryTable.getValueAt(selectedRow, 0);  // Get Record ID of the selected row
        // Open a new frame or dialog to show detailed information for the selected record
        JOptionPane.showMessageDialog(this, "View details for record ID: " + recordId);
        // Alternatively, you can implement a new dialog or frame to show detailed record data.
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecordActionPerformed
        // TODO add your handling code here:
        // Open a new form/dialog to add records
        JOptionPane.showMessageDialog(this, "Open form to add new record.");
    }//GEN-LAST:event_btnAddRecordActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Export records to PDF.");
    }//GEN-LAST:event_btnExportPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NavBtnBack2Dash;
    private javax.swing.JButton NavBtnConsulatation;
    private javax.swing.JButton NavBtnEditProfile;
    private javax.swing.JButton NavBtnviewAppointment;
    private javax.swing.JButton btnAddRecord;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicalHistoryTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
